name: python environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip:
    - plotly 
    - scikit-learn
    - pandas
    - matplotlib
    - numpy
    - scipy
    - sklearn
